name: deploy
on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t rvrbk/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true rvrbk/docker-react npm test
      - run: docker build -t cygnetops/multi-client-10-14 ./client
      - run: docker build -t cygnetops/multi-nginx-10-14 ./nginx
      - run: docker build -t cygnetops/multi-server-10-14 ./server
      - run: docker build -t cygnetops/multi-worker-10-14 ./worker
      - run: docker push cygnetops/multi-client-10-14
      - run: docker push cygnetops/multi-nginx-10-14
      - run: docker push cygnetops/multi-server-10-14
      - run: docker push cygnetops/multi-worker-10-14
      - name: deploy
        run: zip -r deploy.zip . -x '*.git*'
      - name: beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          existing_bucket_name: elasticbeanstalk-us-east-1-252439019993
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip