name: deploy
on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #- run: docker build -t rvrbk/docker-react -f Dockerfile.dev .
      #- run: docker run -e CI=true rvrbk/docker-react npm test
      - name: deploy
        run: zip -r deploy.zip . -x '*.git*'
      - name: beanstalk
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: blaat
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          existing_bucket_name: elasticbeanstalk-us-east-1-252439019993
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip