name: test
on:
  push:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build dockerfile
      run: docker build -t rvrbk/react-test -f Dockerfile.dev .
    - name: Run tests
      run: docker run -e CI=true rvrbk/react-test npm test