name: test
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build dockerfile
      run: docker build -t rvrbk/react-test -f ./client/Dockerfile.dev ./client
    - name: Run tests
      run: docker run -e CI=true rvrbk/react-test npm test